version: '3.8'

services:
  minebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minebot
    ports:
      - "3000:3000"
      - "9050:9050"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
