version: '3.8'

services:
  minebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minebot
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/app # Mount the current directory to /app in the container
    stdin_open: true
    tty: true
